spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dev
    name: sa
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 20
    hibernate:
      ddl-auto: validate
    database: h2
    open-in-view: false
